name: 2. Publish Documentation
env:
  DOTNET_VERSION: '8.0'
  DOTNET_VERSION_TOOL: '6.0'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Bank
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configurando la versi贸n de NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Compatibilidad con .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION_TOOL }}
    - name: Actualizar DocFx y dll2mmd
      run: |
        dotnet tool update -g docfx
        dotnet tool update -g dll2mmd
    - name: Restore & Build project
      run: |
        dotnet restore Bank.Domain/Bank.Domain.csproj
        dotnet build Bank.Domain/Bank.Domain.csproj --configuration Release
    - name: Generar diagrama de clases con dll2mmd
      run: |
        dll2mmd -f Bank.Domain/bin/Release/net8.0/Bank.Domain.dll -o disenio.md
    - name: Generate coverage Report
      run: |
        dotnet test --collect:"XPlat Code Coverage"
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:./*/*/*/coverage.cobertura.xml" "-targetdir:Cobertura" -reporttypes:MarkdownSummaryGithub
    - name: Inicializar DocFX
      run: |
        docfx init -y
    - name: Limpiar el directorio _site
      run: |
        rm -rf _site/*
    - name: Modificar archivo docfx.json para que la salida de metadatos sea en 'docs' y la construcci贸n en '_site'
      run: |
        cat > docfx.json <<EOF
        {
          "$schema": "https://raw.githubusercontent.com/dotnet/docfx/main/schemas/docfx.schema.json",
          "metadata": [
            {
              "src": [
                {
                  "src": ".",
                  "files": [
                    "**/*.csproj"
                  ]
                }
              ],
              "dest": "_api"
            }
          ],
          "build": {
            "content": [
              {
                "files": [
                  "**/*.{md,yml}"
                ],
                "exclude": [
                  "_site/**"
                ]
              }
            ],
            "resource": [
              {
                "files": [
                  "images/**"
                ]
              }
            ],
            "output": "_site",
            "template": [
              "default",
              "modern"
            ],
            "globalMetadata": {
              "_appName": "Bank.App",
              "_appTitle": "Bank App",
              "_enableSearch": true,
              "pdf": true
            }
          }
        }
        EOF
    - name: VER JSON
      run: cat docfx.json
    - name: Modificar archivo toc.yml
      run: |
        cat > toc.yml <<EOF
        - name: Docs
          href: docs/
        EOF
    - name: Modificar archivo index.md
      run: |
        cat > index.md <<EOF
        ---
        _layout: landing
        ---

        # This is the **HOMEPAGE**.

        ## [Pruebas de Cobertura](Cobertura/index.html)

        ## [Diagrama de Clases](disenio.md)

        ## [Pruebas Markdown](Cobertura/SummaryGithub.md)
        EOF
    - name: Generar documentaci贸n (DocFx)
      run: |
        docfx metadata docfx.json
        docfx build
    - name: Preparar directorio para publicaci贸n
      run: |
        mkdir -p ./.github_pages_docs_staging/docs
        mv _site/* ./.github_pages_docs_staging/docs/
        mv disenio.md ./.github_pages_docs_staging/docs/
        mv Cobertura/ ./.github_pages_docs_staging/docs/
        touch ./.github_pages_docs_staging/docs/.nojekyll
        ls -R ./.github_pages_docs_staging/
    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./.github_pages_docs_staging/
        keep_files: false
